### ISSUE TITLE
Workbox build

### ISSUE THREAD

**Issue by rarous** [topmonks/blendid#1]
Add support for `workbox-build` in bare Blendid.

https://developers.google.com/web/tools/workbox/modules/workbox-build

**Comment by junkycoder** [comment]
FYI @rarous, done. Je tam mala zmena oproti nasi domluve a sice, ze mod injectManifest/generateSW prepinam pomoci `swSrc` v configu - https://github.com/topmonks/blendid/blob/master/gulpfile.js/task-config.js#L15 - ukazalo se totiz, ze ten config je +- stejnej pro obe metody a tohle je kratsi..
