### ISSUE TITLE
BrowserSync - cannot ignore files

### ISSUE THREAD

**Issue by nenadalm** [topmonks/blendid#427]
ignore option (https://browsersync.io/docs/options#option-ignore) doesn't work because we just listen for every html, js, css file (https://github.com/topmonks/blendid/blob/68174f3426cf667d3e4023d5825f66d0eb58c0da/gulpfile.js/tasks/browserSync.js#L30) instead of using files option (https://browsersync.io/docs/options#option-files).

This might be problematic when e.g. when js files are generated outside of blendid (e.g. using ClojureScript compiler).

**Comment by rarous** [comment]
@nenadalm please, try https://github.com/topmonks/blendid/commit/43e15bece2f53c40b30ddf5444f8e6bc5ff43fb4

**Comment by nenadalm** [comment]
It seems to work. thanks.

there's one more problem though here: https://github.com/topmonks/blendid/commit/68174f3426cf667d3e4023d5825f66d0eb58c0da#diff-c40605d102e6a5a9a5f02245ac1562917e5e8902a6e86d01058ca9fd13bce594L62-R71. When `collectionsDataFunction` is `false` due to `isArray` test (https://github.com/topmonks/blendid/commit/68174f3426cf667d3e4023d5825f66d0eb58c0da#diff-c40605d102e6a5a9a5f02245ac1562917e5e8902a6e86d01058ca9fd13bce594R53), `dataFunction` becomes `false` and the blendid process crashes. (it didn't happen to me before, because I was using blending before the problematic commit).

**Comment by rarous** [comment]
@nenadalm should be fixed now, thank you

**Comment by nenadalm** [comment]
it works now. thanks.
